// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgDla2tCklP1r8VTFTIFL_053Lb6MqFG4',
    appId: '1:271200245003:web:63289d73d80b260e037e0e',
    messagingSenderId: '271200245003',
    projectId: 'analyzer-f6771',
    authDomain: 'analyzer-f6771.firebaseapp.com',
    storageBucket: 'analyzer-f6771.firebasestorage.app',
    measurementId: 'G-DGXKXXYTF7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcaBY36YlM6PBh3Cz2A00OZR6L7MP65Sg',
    appId: '1:271200245003:android:daf4ee9f50193be4037e0e',
    messagingSenderId: '271200245003',
    projectId: 'analyzer-f6771',
    storageBucket: 'analyzer-f6771.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvN5Pzni3GVMPgRbiG9kqXD8CNGBg_ed8',
    appId: '1:271200245003:ios:b08bca800fd95a9a037e0e',
    messagingSenderId: '271200245003',
    projectId: 'analyzer-f6771',
    storageBucket: 'analyzer-f6771.firebasestorage.app',
    iosBundleId: 'com.example.analyzer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvN5Pzni3GVMPgRbiG9kqXD8CNGBg_ed8',
    appId: '1:271200245003:ios:b08bca800fd95a9a037e0e',
    messagingSenderId: '271200245003',
    projectId: 'analyzer-f6771',
    storageBucket: 'analyzer-f6771.firebasestorage.app',
    iosBundleId: 'com.example.analyzer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgDla2tCklP1r8VTFTIFL_053Lb6MqFG4',
    appId: '1:271200245003:web:a572f674322879bd037e0e',
    messagingSenderId: '271200245003',
    projectId: 'analyzer-f6771',
    authDomain: 'analyzer-f6771.firebaseapp.com',
    storageBucket: 'analyzer-f6771.firebasestorage.app',
    measurementId: 'G-T3409N5VG4',
  );
}
